### ISSUE TITLE
Duplicate chat msg and not showing notification on first time

### ISSUE THREAD

**Issue by MPmsg91** [iamrajendra/space-we_fixed-it#2]
VIVO 1901
Android 9 
my chat msg is showing twice also, I have not to get notification of chat msg.

**Comment by iamrajendra** [comment]
This is a server-side, you have to contact with a server team

**Comment by iamrajendra** [comment]
This is a server-side, you have to contact with a server team

**Comment by iamrajendra** [comment]
This is a server-side, you have to contact with a server team

**Comment by iamrajendra** [comment]
This is a server-side, you have to contact with a server team
